demos: add a check for minimum host gcc
VSDK build system requires a minimum host gcc version. If this
requirement is not met, the VSDK build will fail with the following
linker error:

libs/apex/acf_offline/src/acf_process_desc_apu.cpp:338: undefined
reference to `__cxa_throw_bad_array_new_length'

The customer would not have many options to understand the root cause of
the problem and apply the fix to upgrades the host's gcc.

This change add a checker for the minimum required host gcc version. If
not found, a clear error message is printed:

ERROR: apex-add-1.0-r0 do_configure: Host gcc version (5.4) must be >= 4.9

Issue: ALB-3115

Signed-off-by: Catalin Udma <catalin-dan.udma@nxp.com>